### ISSUE TITLE
Readme or an example

### ISSUE THREAD

**Issue by sidouglas** [NastuzziSamy/ulauncher-custom-scripts#1]
How do you use this ulauncher extension?

Thanks.

**Comment by Amtilaw** [comment]
So yes it need a readme for sure.
I understand how to use it, go in ~/.config/ulauncher and edit scripts.json

To add a script look how I did, just replace with good path.
[
    0     {
    1         "name": "No scripts",
    2         "description": "Select to edit scripts",
    3         "icon": null,
    4         "script": "xdg-open ~/.config/ulauncher/scripts.json",
    5         "default_arguments": [
    6  
    7         ]
    8     }
    9 ,
   10     {
   11         "name": "xampp",
   12         "description": "xampp run",
   13         "icon": null,
   14         "script": "xdg-open ~/.config/ulauncher/xamppStart.sh",
   15         "default_arguments": [
   16  
   17         ]
   18     }
   19 ]

**Comment by NastuzziSamy** [comment]
Hi, I'll make READMEs for all extensions I've developed this we 😉

**Comment by NastuzziSamy** [comment]
Hi @sidouglas I uploaded a README :)

**Comment by metehan** [comment]
Could you also explain how icons are working because I linked an icon but didn't work `"icon" = "~/icons/computer-96.png"` what is wrong with this?

**Comment by NastuzziSamy** [comment]
@metehan you should open a new issue for this but your icons must be defined with full paths
