### ISSUE TITLE
The extension exited instantly.

### ISSUE THREAD

**Issue by jyotirmaybarman** [NastuzziSamy/ulauncher-custom-scripts#4]
Something seems wrong here...!!! on fedora 34 using X11 
![image](https://user-images.githubusercontent.com/56916274/120106732-dd210900-c17b-11eb-80c3-1a5a5cfe72af.png)

**Comment by NastuzziSamy** [comment]
Hi @JyotirmayBarman , can you give more data from your logs ? Thanks
