### ISSUE TITLE
No script appears. Only "Loading..." 

### ISSUE THREAD

**Issue by DiegoBari** [NastuzziSamy/ulauncher-custom-scripts#7]
I have installed the extension, and copied the example scripts into `~/.config/ulauncher/scripts.json`
When writing the keyword "sh" in ulauncher, only the icon assigned with the legend "**Loading ...**" appears but nothing happens. 
The script appears only when tipping.

![2021-07-08_02-27](https://user-images.githubusercontent.com/18667115/124867233-12e3b980-df94-11eb-84f8-3bfecb758f79.png)

**Comment by kushraj** [comment]
same behaviour here too, was working before without any problem

**Comment by femto-code** [comment]
same here

**Comment by MikeRock** [comment]
Hi. I added a quick fix. 

You need to go to where the extension is stored and edit a line in `src/scripts.py`:

https://github.com/NastuzziSamy/ulauncher-custom-scripts/blob/master/src/scripts.py#L9

to

` self.query =  params.pop(0) if len(params) > 0 else ""`

Hope that helps

**Comment by angelbt91** [comment]
> Hi. I added a quick fix.
> 
> You need to go to where the extension is stored and edit a line in `src/scripts.py`:
> 
> https://github.com/NastuzziSamy/ulauncher-custom-scripts/blob/master/src/scripts.py#L9
> 
> to
> 
> ` self.query = params.pop(0) if len(params) > 0 else ""`
> 
> Hope that helps

This solved the issue for me. Doesn't this "Loading..." problem affect every user? Maybe this should be applied in a PR (I can do it myself if anybody confirms that this issue is common to all users).

Thanks!

**Comment by angelbt91** [comment]
> yes I am facing same loading problem too

So, I saw [you already forked the repo and applied the change](https://github.com/directspeed/ulauncher-custom-scripts). Do you want to make that PR yourself, or you prefer me to do it?

**Comment by brunetton** [comment]
@NastuzziSamy Don't you maintain this repo anymore ? Would you merge this [PR](https://github.com/NastuzziSamy/ulauncher-custom-scripts/compare/master...directspeed:ulauncher-custom-scripts:master) ?

**Comment by brunetton** [comment]
@directspeed I just tried your fork but faced another error:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/bruno/.local/share/ulauncher/extensions/com.github.directspeed.ulauncher-custom-scripts/main.py", line 29, in on_event
    results, params = launcher.get_first_scripts()
  File "/home/bruno/.local/share/ulauncher/extensions/com.github.directspeed.ulauncher-custom-scripts/src/scripts.py", line 36, in get_first_scripts
    return self.config[:MAX_SCRIPTS], []
TypeError: unhashable type: 'slice'
```

(no customization made to the sample ~/.config/ulauncher/scripts.json script)

**Comment by brunetton** [comment]
> @directspeed I just tried your fork but faced another error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
>     self.extension.trigger_event(event)
>   File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
>     action = listener.on_event(event, self)
>   File "/home/bruno/.local/share/ulauncher/extensions/com.github.directspeed.ulauncher-custom-scripts/main.py", line 29, in on_event
>     results, params = launcher.get_first_scripts()
>   File "/home/bruno/.local/share/ulauncher/extensions/com.github.directspeed.ulauncher-custom-scripts/src/scripts.py", line 36, in get_first_scripts
>     return self.config[:MAX_SCRIPTS], []
> TypeError: unhashable type: 'slice'
> ```
> 
> (no customization made to the sample ~/.config/ulauncher/scripts.json script)

Fixed [here](https://github.com/NastuzziSamy/ulauncher-custom-scripts/issues/10)
