### ISSUE TITLE
How to customize the icon?

### ISSUE THREAD

**Issue by angelbt91** [NastuzziSamy/ulauncher-custom-scripts#8]
Hello!

Maybe I'm missing the explanation, but I can't figure out how to put a custom icon on an script, or if it needs to be an specific format or have specific dimensions.

Thanks for your help!

**Comment by NastuzziSamy** [comment]
Hi @angelbt91 , you need to put the path of your icon in the icon field: 

https://github.com/NastuzziSamy/ulauncher-custom-scripts#script-file
